model:
  min_confidence: 1e-6
  latent_dims: 512
  first_layer_size: [4, 4]
  conv_channels: 512
  fc_layers: 512
  num_layers: 6
  num_groups: 8

trainer:
  num_dataloaders: 16
  learning_rate: 1e-4
  epsilon: 1e-6

training_stages:
  # - num_layers: 0
  #   epochs: 1
  #   batch_size: 1024
  #   batches_between_image_log: 10
  # - num_layers: 1
  #   epochs: 2
  #   batch_size: 1024
  #   batches_between_image_log: 10
  - num_layers: 2
    epochs: 5
    batch_size: 256
    batches_between_image_log: 5
  - num_layers: 3
    epochs: 10
    batch_size: 64
    batches_between_image_log: 5
  - num_layers: 4
    epochs: 3
    batch_size: 16
    batches_between_image_log: 20
  - num_layers: 5
    epochs: 2
    batch_size: 8
    batches_between_image_log: 20
  - num_layers: 6
    epochs: 4
    batches_between_image_log: 10
    batch_size: 1
