model:
  min_confidence: 1e-6
  latent_dims: 512
  first_layer_size: [4, 4]
  conv_channels: 512
  fc_layers: 512
  num_layers: 6
  num_groups: 8

trainer:
  num_dataloaders: 16
  learning_rate: 1e-4
  epsilon: 1e-6

training_stages:
  - num_layers: 1
    epochs: 1
    batch_size: 64
    batches_between_image_log: 20
  - num_layers: 2
    epochs: 5
    batch_size: 32
    batches_between_image_log: 20
  - num_layers: 3
    epochs: 20
    batch_size: 32
    batches_between_image_log: 20
  - num_layers: 4
    epochs: 10
    batch_size: 20
    batches_between_image_log: 20
  - num_layers: 5
    epochs: 10
    batch_size: 6
    batches_between_image_log: 20
  - num_layers: 6
    epochs: 10
    batches_between_image_log: 10
    batch_size: 2
